### ISSUE TITLE
Problems building within windows

### ISSUE THREAD

**Issue by wellcaffeinated** [PyO3/maturin#274] opened 2020-02-28 23:14 UTC
I'm trying to compile my pyo3 library with maturin, and it works great in OS X. But when I boot up a windows virtual machine and try to execute the same build, i run into issues.

<img width="1265" alt="Screen Shot 2020-02-28 at 4 11 08 PM" src="https://user-images.githubusercontent.com/1128935/75594258-63184680-5a45-11ea-9fbe-331ef8a828de.png">

Any ideas as to what could be going on? or how i could further debug the issue?

Using maturin 0.7.7

Here's the repo:
https://github.com/kshalm/spdcalc/tree/v2.0/python

**Comment by konstin** [comment] 2020-03-06 14:34
Duplicate of #271

**Closed by konstin** 2020-03-06 14:34 UTC
