### ISSUE TITLE
maturin build raise error "Cargo didn't build a cdylib" in version0.13.4

### ISSUE THREAD

**Issue by TeenWolfBB** [PyO3/maturin#1144] opened 2022-09-27 08:23 UTC
### Bug Description

I was using ```maturin```(version:0.13.4) to build a rust project with ```crate-type = ["cdylib"]``` in the ```lib``` section of my ```Cargo.toml```.
And get a error ```maturin failed
  Caused by: Cargo didn't build a cdylib. Did you miss crate-type = ["cdylib"] in the lib section of your Cargo.toml?``` with command ```maturin build -rm Cargo.toml```.
But no error with ```maturin build -rm Cargo.toml``` with version 0.13.3.

### Your Python version (`python -V`)

3.10.6

### Your pip version (`pip -V`)

22.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. build a rust project with ```crate-type = ["cdylib"]``` in the ```lib``` section of ```Cargo.toml```.
2. use ```maturin``(version:0.13.4) to run ```maturin build -rm Cargo.toml```.
3. then get error ```maturin failed
  Caused by: Cargo didn't build a cdylib. Did you miss crate-type = ["cdylib"] in the lib section of your Cargo.toml?``` .

**Comment by messense** [comment] 2022-09-27 08:24
Duplicate of #1141, already fixed in v0.13.5.

**Closed by messense** 2022-09-27 08:24 UTC
Labels: bug
