### ISSUE TITLE
build matrix for wheels?

### ISSUE THREAD

**Issue by trim21** [PyO3/maturin#2411] opened 2024-12-23 19:29 UTC
I'm updating ci build from opendal and we release `cp310-manylinux`,`cp311-abi3`,`cp313-cp313t-manylinux` wheels.

`cp310-manylinux` and `cp313-cp313t-manylinux` can be conbined as `build -o dist -i python3.10 -i python3.13t`, but `abi3` feature is enabled with `--features=abi3` make it must exists in a seprated command, and therefore make it build whole project twice.

Is there any possible to make then unified?

for example: 

```toml
[[tool.matruin.matrix]]
interpreter = '3.10'

[[tool.matruin.matrix]]
interpreter = '3.13t'

[[tool.matruin.matrix]]
interpreter = '3.11'
features = ['abi3']
```

**Comment by messense** [comment] 2024-12-24 00:31
Duplicate of https://github.com/PyO3/maturin-action/issues/166

The abi3 issue is a known bug of `pyo3`: https://github.com/PyO3/maturin/issues/2385

**Closed by messense** 2024-12-24 00:31 UTC
Labels: enhancement

**Comment by messense** [comment] 2024-12-24 01:14
> `abi3` feature is enabled with `--features=abi3` make it must exists in a seprated command

abi3 feature should be able to coexist with other arguments, even when `abi3` feature is enable, pyo3 will not make use of it: https://github.com/PyO3/pyo3/pull/4733, but it currently does not work well with `generate-import-lib` feature yet, which is #2385 (it's not transfered to pyo3/pyo3 because people will mostly likely lookup maturin issue tracker first for such kind of issues).
