### ISSUE TITLE
Maturin failed Caused by: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by yogh333** [PyO3/maturin#2364] opened 2024-12-04 08:49 UTC
### Bug Description

maturin is used by this project: https://github.com/pvolnov/near-primitives
With recent update from 1.7.6 to 1.7.7, there is an error when building the package (see https://github.com/pvolnov/near-primitives/issues). 
Forcing the version to 1.7.6 seems to work.

### Your maturin version (`maturin --version`)

1.7.7

### Your Python version (`python -V`)

3.9.18

### Your pip version (`pip -V`)

24.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

```
git clone git@github.com:pvolnov/near-primitives.git
cd near-primitives
pip install .
```

**Comment by messense** [comment] 2024-12-04 08:56
Duplicate of #2363 

You have pointed `python-source` to a non-existent path in https://github.com/pvolnov/near-primitives/blob/3be30777a24dcd6feb75fdc55abff120983c069a/pyproject.toml#L45

**Closed by messense** 2024-12-04 08:56 UTC
Labels: bug
