### ISSUE TITLE
Maturin is buggy when Cargo.toml sets `license-file.workspace = true`

### ISSUE THREAD

**Issue by sxlijin** [PyO3/maturin#2116] opened 2024-06-19 22:48 UTC
### Bug Description

Users of our package, `baml-py`, see this on install:

```
Warning: Validation of the RECORD file of
baml_py-0.40.0-cp38-abi3-macosx_11_0_arm64.whl failed. Please report to
the maintainers of that package so they can fix their build process.
Details:
In
/Users/sam/baml/engine/target/wheels/baml_py-0.40.0-cp38-abi3-macosx_11_0_arm64.whl,
baml_py-0.40.0.dist-info/license_files/LICENSE is not mentioned in
RECORD
```

Our repo, as of the 0.40.0 release, is set up as follows:

```
engine/
  Cargo.toml # the workspace
  LICENSE
  language_client_python/
    Cargo.toml # has license-file.workspace = true
    LICENSE
    pyproject.toml # project.license = LICENSE
    python_src/ # tool.maturin.python-source points here
    src/ # rust points here
```

Switching language_client_python/Cargo.toml to use SPDX directives a la `license = "Apache-2.0"` appears to fix the error for us (see https://github.com/BoundaryML/baml/pull/695)

### Your maturin version (`maturin --version`)

1.6.0

### Your Python version (`python -V`)

Python 3.12.3

### Your pip version (`pip -V`)

Poetry (version 1.8.3)

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

`maturin=debug` logs: https://gist.github.com/sxlijin/65165e44bba9167b4c03cc2ab15d0005

repro instructions (have not tested, you'll need to tweak for your machine, but it looks reasonably correct)

```
git clone https://github.com/boundaryml/baml
cd baml && git checkout f93e1cf && cd ..
mkdir sandbox-python-repro && cd sandbox-python-repro
cat >pyproject.toml <<EOF
[tool.poetry]
name = "sandbox-python-repro"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
maturin = "^1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
EOF
poetry run maturin build --manifest-path ../baml/engine/language_client_python/Cargo.toml && poetry add ../baml/engine/target/wheels/baml_py-0.40.0-cp38-abi3-macosx_11_0_arm64.whl
```

**Comment by messense** [comment] 2024-06-20 01:11
Duplicate of #2066

**Closed by messense** 2024-06-20 01:11 UTC
Labels: bug
