### ISSUE TITLE
Support PEP 639

### ISSUE THREAD

**Issue by flying-sheep** [PyO3/maturin#1361] opened 2022-12-18 15:48 UTC
[PEP 639](https://peps.python.org/pep-0639/) makes specifying a license much easier for users, excerpt:

> A top-level string value is defined for the `license` key in the `[project]` table, which is specified to be a valid SPDX license expression

> If the `license-files` key is not present and not explicitly marked as `dynamic`, tools MUST assume a default value of the following:
> ```toml
> license-files.globs = ["LICEN[CS]E*", "COPYING*", "NOTICE*", "AUTHORS*"]
> ```

So one can simply specify `license = 'MIT'`, create a `LICENSE.md` or so, and call it a day.

**Comment by messense** [comment] 2022-12-18 20:01
Duplicate of #861

**Closed by messense** 2022-12-18 20:01 UTC
Labels: enhancement
