### ISSUE TITLE
Support for different package managers like poetry, uv, rye

### ISSUE THREAD

**Issue by itsmeadarsh2008** [PyO3/maturin#2148] opened 2024-07-17 05:50 UTC
I want the support for uv more specifically. It is a Rust package manager for Python. The maturin uses pip by default.

**Comment by messense** [comment] 2024-07-17 05:55
Duplicate of #1959.

Closing this, please open a more specific issue if you have other problems.

**Closed by messense** 2024-07-17 05:55 UTC
Labels: enhancement
