### ISSUE TITLE
Crash report: auditwheel No such file or directory

### ISSUE THREAD

**Issue by hombit** [PyO3/maturin#793] opened 2022-02-03 18:31 UTC
### Bug Description

I tried to build a wheel for my package inside aarch64 manylinux2014 container

Crash report:

```toml
name = 'maturin'
operating_system = 'unix:CentOS'
crate_version = '0.12.6'
explanation = '''
Panic occurred in file 'src/auditwheel/repair.rs' at line 16
'''
cause = 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })'
method = 'Panic'
backtrace = '''

   0:   0x431758 - core::result::unwrap_failed::h8426e3038690cbd0
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616
   1:   0x5ffaa4 - maturin::auditwheel::repair::find_external_libs::h7e7cb85f7ad128e0
   2:   0x5347f4 - maturin::build_context::BuildContext::auditwheel::hf95c7113299f6a82
   3:   0x5368e0 - maturin::build_context::BuildContext::build_binding_wheels::h8ef480a44f182609
   4:   0x533a90 - maturin::build_context::BuildContext::build_wheels::hc4457e80e9490898
   5:   0x435430 - maturin::run::h8ec1bf88cf675f35
   6:   0x437388 - maturin::main::h0afd0e6fcff1a136
   7:   0x443810 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbcea5cd4a1853f1a
   8:   0x43c4ac - std::rt::lang_start::{{closure}}::h897929e2471d64cb
   9:   0xd65d14 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc55fd9b99064b010
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259
                 - std::panicking::try::do_call::he05ba5aa3d103aad
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403
                 - std::panicking::try::h2c702e3ae5c03a1a
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367
                 - std::panic::catch_unwind::h28c35660b05e2bb9
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133
                 - std::rt::lang_start_internal::{{closure}}::h7f5f0978f5a86cc9
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128
                 - std::panicking::try::do_call::h82c5279b929cc8b4
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403
                 - std::panicking::try::h2ecca7d1bcb56fcb
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367
                 - std::panic::catch_unwind::h7f565371d49c70b6
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133
                 - std::rt::lang_start_internal::h9d478e200477864b
                at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128
  10:   0x43a4d0 - main'''
```

### Your Python version (`python -V`)

Python 3.7

### Your pip version (`pip -V`)

pip 21.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Run manylinux container:
`docker run --rm -ti quay.io/pypa/manylinux2014_aarch64:2021-12-12-e5100b5`

Commands to run inside the container:
```sh
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
yum install -y openssl-devel gsl-devel
PATH="$PATH:$HOME/.cargo/bin"
git clone https://github.com/light-curve/light-curve-python
cd light-curve-python
git checkout fca246b4544aa2b719e3ea150e7ef063fae7a667  # Current master
cd light-curve
python3.7 -mpip wheel . --no-deps
```

**Comment by messense** [comment] 2022-02-04 02:49
The root cause is that `quay.io/pypa/manylinux2014_aarch64:2021-12-12-e5100b5` contains a `LD_LIBRARY_PATH=/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/usr/local/lib64` env var but `/opt/rh/devtoolset-10/root/usr/lib64/dyninst` does not exist.

Fixed in https://github.com/messense/lddtree-rs/commit/c7a3007971ee154a2ca85ce5ffc1e1a38e54a79b

**Closed** 2022-02-04 03:52 UTC
Labels: bug

**Comment by messense** [comment] 2022-02-04 04:47
Please try [0.12.7_beta.8](https://pypi.org/project/maturin/0.12.7_beta.8/).

**Comment by hombit** [comment] 2022-02-04 13:16
It works, thank you!
