### ISSUE TITLE
Can't compile using `maturin develop` on macOS(M2 chip)

### ISSUE THREAD

**Issue by dzvon** [PyO3/maturin#1013] opened 2022-07-19 06:51 UTC
### Bug Description

I tried follow up the example(string_num) in https://github.com/PyO3/pyo3. It shows a bunch of errors when I run `maturin develop`. Here is a screenshot of the error, not all of them.

![image](https://user-images.githubusercontent.com/3402811/179683455-37c553cc-bb9c-44b8-85f3-89e5774da8db.png)

The most important information here is `x86_64-apple-darwin`, why the compile target is `x86_64-apple-darwin`? I run those code on macOS with M2 chip, the target should be `aarch64-apple-darwin`.

BTW, I also tried `maturin develop --target aarch64-apple-darwin`, unfortunately, it doesn't work.

### Your Python version (`python -V`)

Python 3.8.9

### Your pip version (`pip -V`)

pip 22.1.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

https://github.com/PyO3/pyo3#using-rust-from-python

**Comment by messense** [comment] 2022-07-19 07:11
Looks like you are using a x86_64 Python virtualenv. What's the output of `python3 -c 'import platform; print(platform.platform())'`?

**Comment by dzvon** [comment] 2022-07-19 07:25
```
Python 3.8.9 (default, Jul 19 2021, 09:37:30)
[Clang 13.0.0 (clang-1300.0.27.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig; print(sysconfig.get_platform(), end='')
macosx-10.14.6-arm64>>>
```

**Comment by messense** [comment] 2022-07-19 07:36
What's the output of `rustc -vV`?

**Comment by dzvon** [comment] 2022-07-19 07:36
```
➜  ~ rustc -vV
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: aarch64-apple-darwin
release: 1.62.0
LLVM version: 14.0.5
```

**Comment by dzvon** [comment] 2022-07-19 08:01
Gotcha, my scenario is arm64 Python + aarch64-apple-darwin, but the factual compile target is `x86_64-apple-darwin`

**Comment by messense** [comment] 2022-07-19 08:03
See https://github.com/PyO3/maturin/pull/1015#discussion_r924166748

**Comment by messense** [comment] 2022-07-19 08:08
Architecture can change on arm64 macOS depending on how you invoke a program. For example

```bash
$ /Applications/Xcode.app/Contents/Developer/usr/bin/python3.8 -c "import sysconfig; print(sysconfig.get_platform(), end='')"
macosx-10.14-arm64
$ arch -x86_64 /Applications/Xcode.app/Contents/Developer/usr/bin/python3.8 -c "import sysconfig; print(sysconfig.get_platform(), end='')"
macosx-10.14-x86_64
```

So it's better to get the values from Rust code.

**Comment by dzvon** [comment] 2022-07-19 08:11
> See [#1015 (comment)](https://github.com/PyO3/maturin/pull/1015#discussion_r924166748)

already reply the output, don't know if you can see it.

**Comment by dzvon** [comment] 2022-07-19 08:23
<img width="790" alt="image" src="https://user-images.githubusercontent.com/3402811/179703244-95f2348b-d01b-4ad9-b26c-825e2b358f82.png">

**Comment by messense** [comment] 2022-07-19 08:24
Pending comments are not visible to others.

**Comment by dzvon** [comment] 2022-07-19 08:27
Sorry, I don't know why my message is *pending*, I just reply your message and click comment button.

**Comment by messense** [comment] 2022-07-19 08:31
You need to submit the review.

See also https://github.com/github-community/community/discussions/10369

**Comment by dzvon** [comment] 2022-07-19 08:34
Thank you so much! @messense

**Comment by sahuagin** [comment] 2022-08-02 16:18
I don't know if this is related, but I suspect it is. Using maturin in a project for a few months successfully. Recently (this week) `maturin develop` started to fail, while `maturin build` succeeded. Find that `pip install maturin` fails, while `cargo install maturin` succeeds.
Looked into a lot of things, but removing an explicit target from ~/.cargo/config.toml resulted in `pip install maturin` succeeding.
The target had been specified as there are/were two different targets using the same build directories and this was to prevent collisions.
The change was removing, 'build.target = "x86_64-unknown-freebsd"' from ~/.cargo/config.toml. The project is currently building to see if it now succeeds when calling `maturin develop`.
Looking at the delta between 0.13.1 and 0.13.0 there is a comment regarding honoring specified targets; I suspect this is causing the wheel builds to fail in tmp after building, as the directory path isn't what it thinks it may be.

**Comment by messense** [comment] 2022-08-03 02:40
> Looking at the delta between 0.13.1 and 0.13.0 there is a comment regarding honoring specified targets; I suspect this is causing the wheel builds to fail in tmp after building, as the directory path isn't what it thinks it may be.

That only applies to `maturin develop --target xxx`. Can you open a new issue with more detailed steps to reproduce?

**Comment by messense** [comment] 2022-08-03 02:41
Closing because I can't not reproduce this issue, @dzvon feel free to reopen if you have more detailed steps (include how did you install Python/Rust etc.) to reproduce this issue.

**Closed by messense** 2022-08-03 02:41 UTC
Labels: bug

**Comment by timgrossmann** [comment] 2024-02-27 13:30
Same issue, no solution findable anywhere...
Seems like Maturin just won't work with Mac M2

**Comment by messense** [comment] 2024-02-27 13:37
As I have said before, please provide more detailed steps in a new issue.
