### ISSUE TITLE
Show helpful error when running maturin develop on non-maturin project

### ISSUE THREAD

**Issue by SV-97** [PyO3/maturin#1332] opened 2022-12-05 11:10 UTC
Running `maturin develop` on a "normal" (non maturin-based) rust project yields a crash with a big error message because of an `Option::unwrap()` on `None` in `src/build_contexts.rs:683`.

It may help users to notify them that they may be outside a maturin project rather than printing the generic error about sending in the log files etc.

[log.txt](https://github.com/PyO3/maturin/files/10153556/log.txt)

**Comment by messense** [comment] 2022-12-05 11:14
> crate_version = '0.13.2'

You are using a rather old version of maturin, have you tried v0.14, does it still happens?

**Comment by messense** [comment] 2022-12-05 11:18
Duplicate of #1061 which was already fixed in https://github.com/PyO3/maturin/commit/d0c2b7cfd2579b9f421bf9be9f987b6d1fd24e10

**Closed by messense** 2022-12-05 11:18 UTC
Labels: enhancement

**Comment by SV-97** [comment] 2022-12-05 11:50
> You are using a rather old version of maturin, have you tried v0.14, does it still happens?

Sorry I had two versions of maturin installed and didn't notice I was running the old one. With 0.14.4 it shows a warning like
```
Warning: Couldn't find the symbol `PyInit_m` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `m` as module name
```
but finishes the build.
