### ISSUE TITLE
package version suffix dropped in sdist build

### ISSUE THREAD

**Issue by kalzoo** [PyO3/maturin#1662] opened 2023-06-13 17:57 UTC
### Bug Description

In CI, we use maturin to build both the wheel (for linux) and the sdist. We then install the wheel and then the sdist as a smoke test.

When installing the wheel built with `maturin`, the correct version is installed:

```
$ pip3.8 install $CUSTOM_PACKAGE_WHL_PATH
Processing ./target/wheels/custom-package-4.6.2.dev4461435608-cp38-abi3-linux_x86_64.whl
Installing collected packages: custom-package
Successfully installed custom-package-4.6.2.dev4461435608
```

However, when the sdist is installed, that `dev` suffix is dropped:

```
$ pip3.8 install --upgrade $CUSTOM_PACKAGE_SDIST_PATH
Processing ./target/wheels/custom-package-4.6.2.dev4461435608.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: custom-package
  Building wheel for custom-package (pyproject.toml): started
  Building wheel for custom-package (pyproject.toml): still running...
  Building wheel for custom-package (pyproject.toml): finished with status 'done'
  Created wheel for custom-package: filename=custom-package-4.6.2-cp38-abi3-linux_x86_64.whl size=3535733 sha256=37c7e66e197f53e3e152ab29f934990e4c8c942fdba184e34a2baff63e7b25e3
  Stored in directory: /root/.cache/pip/wheels/de/a3/ac/5c4e85edd0dc595a663cad7588dd3cac297a9c4b48dd9d0de6
Successfully built custom-package
Installing collected packages: custom-package
  Attempting uninstall: custom-package
    Found existing installation: custom-package 4.6.2.dev4461435608
    Uninstalling custom-package-4.6.2.dev4461435608:
      Successfully uninstalled custom-package-4.6.2.dev4461435608
Successfully installed custom-package-4.6.2 ## COMMENT <--- Note that dev suffix is dropped
```

Searching the sdist, that `dev`-less version is not present anywhere. The `dev` suffix is present in all 3 locations. I've reproduced this outside of the container, and that `4.6.2` version only shows up when `pip` rebuilds the manifest as part of building the wheel from sdist.

This is not just a matter of a bad pip version in CI; that sdist is published to a private PyPI instance, and all consumers have been reporting the same problem on installation (where `--use-deprecated legacy-resolver` is necessary to install)

This occurs with both of these patterns in Cargo.toml:

* `4.6.2-devXXXX`
* `4.6.2-dev-XXXX`

This did _not_ occur with `ghcr.io/pyo3/maturinv0.14.0-beta.3`. From CI logs:

```
Successfully installed custom-package-4.2.1.dev4208128931
```

All versions tried:

* v1.0.1 -> version mismatch
* v0.15.2 -> version mismatch
* v0.15.1, v0.15.0 -> different error preventing build: `cargo metadata exited with an error: error: failed to get other-package as a dependency of package `custom-package v4.6.2-dev4466734782`
* v0.14.0-beta.3 -> version correctly matches (from past CI logs)

### Your maturin version (`maturin --version`)

ghcr.io/pyo3/maturin:v1.0.1, also with v0.15.2

### Your Python version (`python -V`)

ghcr.io/pyo3/maturin:v1.0.1, also with v0.15.2

### Your pip version (`pip -V`)

ghcr.io/pyo3/maturin:v1.0.1, also with v0.15.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Please see description

**Comment by messense** [comment] 2023-06-14 13:14
I'm unable to reproduce this issue with maturin 1.1.0 in `pyo3-pure` test project

https://github.com/PyO3/maturin/blob/23c654de7efde14edcb8649f08f9821fd86c1fb9/test-crates/pyo3-pure/pyproject.toml#L18

I have changed `version` to `0.1.0.dev123456`

```bash
$ python --version
Python 3.11.0
$ pip --version
pip 23.1.2
$ pip install dist/pyo3_pure-0.1.0.dev123456.tar.gz
Processing ./dist/pyo3_pure-0.1.0.dev123456.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyo3_pure
  Building wheel for pyo3_pure (pyproject.toml) ... done
  Created wheel for pyo3_pure: filename=pyo3_pure-0.1.0.dev123456-cp37-abi3-macosx_11_0_arm64.whl size=234368 sha256=8558a3a24206af7ec96ca41a7ae5b69241046ca67ea6d7fc5c0b85d0d2eb8bb8
  Stored in directory: /Users/messense/Library/Caches/pip/wheels/5d/ee/6c/a9ddc477d52355fadf430a700a85a963e8aad083f5639d0b14
Successfully built pyo3_pure
Installing collected packages: pyo3_pure
Successfully installed pyo3_pure-0.1.0.dev123456
```

**Comment by kalzoo** [comment] 2023-06-14 17:48
Thanks @messense - I'll keep looking into it and report back when I find the cause.

**Comment by messense** [comment] 2023-08-06 11:05
Closing for now, please reopen when you find the cause.

**Closed by messense** 2023-08-06 11:05 UTC
Labels: bug, sdist
