### ISSUE TITLE
Add gitlab ci support

### ISSUE THREAD

**Issue by osintalex** [PyO3/maturin#2014] opened 2024-03-28 12:47 UTC
Would be awesome to have support for generating a CI template file with a command like `maturin generate-ci gitlab`. At present, you can only do `maturin generate-ci github`. 

I would use this to publish python packages with multi-platform support in CI. Personally, I would probably use this as a template which I'd then tweak to be more compatible with existing CI workflows where I work. I would therefore want the gitlab template to be easy to modify, expressive, and well documented. 

I will (hopefully) have a pretty bad but working draft implementation of a gitlab ci file for this that could be used as a starting point to get the ball rolling.

**Comment by messense** [comment] 2024-03-28 12:49
Duplicate of #1507, pull requests are welcome!

**Closed** 2024-03-28 12:49 UTC
Labels: enhancement
