### ISSUE TITLE
`maturin new` creates `name` key twice in Cargo.toml

### ISSUE THREAD

**Issue by Hofer-Julian** [PyO3/maturin#1124] opened 2022-09-23 06:57 UTC
### Bug Description

When `maturin new` creates `name` key twice in Cargo.toml

### Your Python version (`python -V`)

Python 3.10.6

### Your pip version (`pip -V`)

pip 22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Run `maturin new -b pyo3 test`
2. It creates a project with the following `Cargo.toml`
```rust
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html[lib]
name = "test"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
```

**Comment by messense** [comment] 2022-09-23 06:58
Duplicate of #1120

**Closed by messense** 2022-09-23 06:58 UTC
Labels: bug
