### ISSUE TITLE
Caused by: Cargo didn't build a cdylib

### ISSUE THREAD

**Issue by jonashaag** [PyO3/maturin#1716] opened 2023-08-05 22:44 UTC
### Bug Description

```
maturin failed
  Caused by: Cargo didn't build a cdylib. Did you miss crate-type = ["cdylib"] in the lib section of your Cargo.toml?
```

### Your maturin version (`maturin --version`)

1.1.0

### Your Python version (`python -V`)

Python 3.11.4

### Your pip version (`pip -V`)

pip 23.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Check out https://github.com/jonashaag/polars/tree/wasm
2. Run `maturin build --target wasm32-unknown-emscripten --profile wasm`

**Comment by messense** [comment] 2023-08-06 01:14
It seems that it's already fixed on `main`, I can't reproduce it from maturin `main` branch.

**Closed by messense** 2023-08-06 01:14 UTC
Labels: bug

**Comment by messense** [comment] 2023-08-06 10:19
Please give maturin v1.2.0 a try.

**Comment by jonashaag** [comment] 2023-08-06 10:37
Thanks, fixed the problem
