### ISSUE TITLE
Regression in cffi binding in 1.6

### ISSUE THREAD

**Issue by pacman82** [PyO3/maturin#2138] opened 2024-07-06 11:48 UTC
### Bug Description

Since version `1.6` wheel builds break for me under both OS-X and Windows. The error reported is that `cffi` is not found to generate the bindings. Version `1.5` works fine.

### Your maturin version (`maturin --version`)

1.6

### Your Python version (`python -V`)

1.10

### Your pip version (`pip -V`)

24.1.1

### What bindings you're using

None

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. `git checkout https://github.com/pacman82/arrow-odbc-py.git`
2. `git reset --hard 475c2af412ab7c9ede3548a19bc90f1dcaf8540e`
3. Setup virtual environment
4. `python -m pip install build`
5. python -m build .

Produces the following output:

(venv) PS C:\repos\arrow-odbc-py> python -m build .      
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - cffi
  - maturin>=1.0,<2.0
* Getting build dependencies for sdist...
* Building sdist...
Running `maturin pep517 write-sdist --sdist-directory C:\repos\arrow-odbc-py\dist`
🍹 Building a mixed python/rust project
🔗 Found cffi bindings
🐍 Using CPython 3.10 at C:\Users\Markus\AppData\Local\Temp\build-env-skco_eqd\Scripts\python.exe to generate the cffi bindings
📡 Using build options profile, bindings from pyproject.toml
📦 Built source distribution to C:\repos\arrow-odbc-py\dist\arrow_odbc-7.0.4.tar.gz
arrow_odbc-7.0.4.tar.gz
* Building wheel from sdist
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - cffi
  - maturin>=1.0,<2.0
* Getting build dependencies for wheel...
* Installing packages in isolated environment:
  - cffi
* Building wheel...
Running `maturin pep517 build-wheel -i C:\Users\Markus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe --compatibility off`
🍹 Building a mixed python/rust project
🔗 Found cffi bindings
🐍 Using CPython 3.10 at C:\Users\Markus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe to generate the cffi bindings
📡 Using build options profile, bindings from pyproject.toml
   Compiling libm v0.2.8
   Compiling autocfg v1.3.0
   Compiling windows_x86_64_msvc v0.52.5
   Compiling cfg-if v1.0.0
   Compiling bitflags v2.6.0
   Compiling once_cell v1.19.0
   Compiling version_check v0.9.4
   Compiling bytes v1.6.0
   Compiling zerocopy v0.7.34
   Compiling hashbrown v0.14.5
   Compiling static_assertions v1.1.0
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling memchr v2.7.4
   Compiling regex-syntax v0.8.4
   Compiling cfg_aliases v0.2.1
   Compiling tracing-core v0.1.32
   Compiling odbc-sys v0.24.0
   Compiling pin-project-lite v0.2.14
   Compiling thiserror v1.0.61
   Compiling ryu v1.0.18
   Compiling unicode-segmentation v1.11.0
   Compiling base64 v0.22.1
   Compiling smol_str v0.2.2
   Compiling cursor-icon v1.1.0
   Compiling dpi v0.1.1
   Compiling raw-window-handle v0.6.2
   Compiling log v0.4.22
   Compiling widestring v1.1.0
   Compiling lexical-util v0.8.5                                                                                                                            
   Compiling getrandom v0.2.15                                                                                                                              
   Compiling winit v0.30.3
   Compiling arrow-schema v52.0.0
   Compiling thread_local v1.1.8                                                                                                                            
   Compiling ahash v0.8.11                                                                                                                                  
   Compiling num-traits v0.2.19                                                                                                                             
   Compiling tracing v0.1.40                                                                                                                                
   Compiling aho-corasick v1.1.3                                                                                                                            
   Compiling lexical-write-integer v0.8.5                                                                                                                   
   Compiling lexical-parse-integer v0.8.6
   Compiling windows-targets v0.52.5                                                                                                                        
   Compiling windows-sys v0.52.0                                                                                                                            
   Compiling lexical-parse-float v0.8.5                                                                                                                     
   Compiling lexical-write-float v0.8.5                                                                                                                     
   Compiling quote v1.0.36                                                                                                                                  
   Compiling syn v2.0.68                                                                                                                                    
   Compiling lexical-core v0.8.5                                                                                                                            
   Compiling num-integer v0.1.46
   Compiling num-complex v0.4.6
   Compiling half v2.4.1
   Compiling chrono v0.4.38
   Compiling atoi v2.0.0
   Compiling regex-automata v0.4.7                                                                                                                          
   Compiling num-bigint v0.4.5                                                                                                                              
   Compiling num-iter v0.1.45
   Compiling thiserror-impl v1.0.61                                                                                                                         
   Compiling num-rational v0.4.2
   Compiling num v0.4.3
   Compiling arrow-buffer v52.0.0
   Compiling regex v1.10.5
   Compiling arrow-data v52.0.0
   Compiling arrow-array v52.0.0
   Compiling winapi-util v0.1.8
   Compiling is-terminal v0.4.12
   Compiling termcolor v1.1.3
   Compiling stderrlog v0.6.0
   Compiling arrow-select v52.0.0
   Compiling arrow-arith v52.0.0
   Compiling arrow-row v52.0.0
   Compiling odbc-api v8.1.1
   Compiling arrow-string v52.0.0
   Compiling arrow-ord v52.0.0
   Compiling arrow-cast v52.0.0
   Compiling arrow v52.0.0                                                                                                                                  
   Compiling arrow-odbc v11.2.0
   Compiling arrow-odbc-py v0.1.0 (C:\Users\Markus\AppData\Local\Temp\build-via-sdist-8mknghh2\arrow_odbc-7.0.4)
    Finished `release` profile [optimized] target(s) in 31.94s
💼 Using the existing cbindgen.toml configuration.
💼 Enforcing the following settings:
   - language = "C"
   - no_includes = true, sys_includes = []
     (#include is not yet supported by CFFI)
   - defines = [], include_guard = None, pragma_once = false, cpp_compat = false
     (#define, #ifdef, etc. is not yet supported by CFFI)

💥 maturin failed
  Caused by: Failed to generate cffi declarations using C:\Users\Markus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: exit code: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'cffi'

Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'C:\\Users\\Markus\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe', '--compatibility', 'off'] returned non-zero exit status 1

**Comment by messense** [comment] 2024-07-07 01:16
Duplicate of #2133, fixed in #2134

**Closed by messense** 2024-07-07 01:16 UTC
Labels: bug

**Comment by pacman82** [comment] 2024-07-07 07:36
Sorry for the duplicate. Thank you, for the quick release!
