### ISSUE TITLE
Support Android with Termux

### ISSUE THREAD

**Issue by programmerjake** [PyO3/maturin#332] opened 2020-07-24 17:55 UTC
"[Termux](https://termux.com/) is an Android terminal emulator and Linux environment app that works directly with no rooting or setup required. A minimal base system is installed automatically - additional packages are available using the APT package manager."

[python-sysconfig.txt](https://github.com/PyO3/maturin/files/4973556/python-sysconfig.txt)

wheel naming scheme: `maturin-0.8.2-cp38-cp38-linux_aarch64.whl`

**Comment by konstin** [comment] 2020-07-29 18:08
aarch64 should be supported since #273. Please open another if something specific about the platform doesn't work

**Comment by programmerjake** [comment] 2020-07-29 18:35
@konstin
maturin 0.8.2

```
$ maturin build --cargo-extra-args=--features=python-extension
💥 maturin failed
  Caused by: The operating system Android is not supported
```

**Comment by konstin** [comment] 2020-07-29 18:39
> 	SO = ".cpython-38.so"
>	SOABI = "cpython-38"

That is definitely an odd platform.

I have no device to test against, but I will accept pull requests adding support for android.

**Comment by messense** [comment] 2021-07-22 06:58
Since https://github.com/PyO3/maturin/pull/538 Android should be recognized as Linux, @programmerjake can you try the latest maturin to see if it works on Termux?

**Comment by programmerjake** [comment] 2021-07-22 07:50
I tried building `power-instruction-analyzer` from the [v0.2.0 git tag](https://salsa.debian.org/Kazan-team/power-instruction-analyzer/-/tree/v0.2.0) using:
```
maturin build --cargo-extra-args=--features=python-extension
```
the build succeeded, but importing the package failed with:
```
ImportError: dlopen failed: cannot locate symbol "PyObject_GenericGetDict" referenced by "/data/data/com.termux/files/usr/lib/python3.9/site-packages/power_instruction_analyzer/power_instruction_analyzer.cpython-39.so"...
```

**Comment by messense** [comment] 2021-07-22 08:01
Great, at least it builds. The `ImportError` don't seem to be related to maturin, maybe try upgrade pyo3 to 0.14?

**Comment by messense** [comment] 2021-08-17 13:56
Since it builds and the import issue isn't directly related to maturin(I think you can report the issue to PyO3), I'm going to close this ticket.

Feel free to reopen if it's somehow caused by maturin.

**Closed by messense** 2021-08-17 13:56 UTC
Labels: enhancement
