### ISSUE TITLE
Microsoft Store version Python supported

### ISSUE THREAD

**Issue by tcztzy** [PyO3/maturin#827] opened 2022-03-03 08:27 UTC
[Microsoft Store version Python](https://docs.python.org/3/using/windows.html#the-microsoft-store-package) provides `python.exe`, `idle.exe` and `pip.exe`, but no `py.exe` launcher. If a user (like me) only installed this package, without the traditional one, will got error because the hard code way to find Python interpreter.
https://github.com/PyO3/maturin/blob/28496e0acf8a0fc6912939fe22c8bbbe60471765/src/python_interpreter.rs#L135

I prefer it to be a feature request instead of bug report, hope you will help people like me.

**Comment by messense** [comment] 2022-03-03 08:32
Duplicate of https://github.com/PyO3/maturin/issues/788

**Closed by messense** 2022-03-03 08:32 UTC
Labels: enhancement

**Comment by messense** [comment] 2022-03-03 08:45
For now you should be work around it by supplying `-i python` arguments.
