### ISSUE TITLE
Maturin fails to compile

### ISSUE THREAD

**Issue by westernwontons** [PyO3/maturin#1496] opened 2023-02-21 14:37 UTC
### Bug Description

When I attempt to update maturin, I get this error:
```bash
    Updating registry 'https://github.com/rust-lang/crates.io-index'

Package  Installed  Latest                              Needs update
maturin  v0.14.12   v0.14.13 (v1.0.0-beta.2 available)  Yes

Updating maturin
    Updating crates.io index
  Installing maturin v0.14.13
   Compiling proc-macro2 v1.0.51
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling libc v0.2.139
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling memchr v2.5.0
   Compiling serde v1.0.152
   Compiling serde_derive v1.0.152
   Compiling autocfg v1.1.0
   Compiling once_cell v1.17.1
   Compiling cc v1.0.79
   Compiling log v0.4.17
   Compiling unicase v2.6.0
   Compiling io-lifetimes v1.0.5
   Compiling proc-macro-error-attr v1.0.4
   Compiling rustix v0.36.8
   Compiling errno v0.2.8
   Compiling proc-macro-error v1.0.4
   Compiling bitflags v1.3.2
   Compiling ring v0.16.20
   Compiling serde_json v1.0.93
   Compiling lazy_static v1.4.0
   Compiling indexmap v1.9.2
   Compiling byteorder v1.4.3
   Compiling heck v0.4.1
   Compiling getrandom v0.2.8
   Compiling typenum v1.16.0
   Compiling regex-syntax v0.6.28
   Compiling encoding_index_tests v0.1.4
   Compiling itoa v1.0.5
   Compiling ryu v1.0.12
   Compiling crossbeam-utils v0.8.14
   Compiling crunchy v0.2.2
   Compiling crc32fast v1.3.2
   Compiling mime_guess v2.0.4
   Compiling os_str_bytes v6.4.1
   Compiling termcolor v1.2.0
   Compiling clap_lex v0.3.1
   Compiling is-terminal v0.4.3
   Compiling terminal_size v0.2.5
   Compiling memoffset v0.7.1
   Compiling generic-array v0.14.6
   Compiling camino v1.1.2
   Compiling adler v1.0.2
   Compiling hashbrown v0.12.3
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling minimal-lexical v0.2.1
   Compiling tiny-keccak v2.0.2
   Compiling pkg-config v0.3.26
   Compiling scopeguard v1.1.0
   Compiling thiserror v1.0.38
   Compiling either v1.8.1
   Compiling strsim v0.10.0
   Compiling untrusted v0.7.1
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling nom v7.1.3
   Compiling miniz_oxide v0.6.2
   Compiling thiserror-impl v1.0.38
   Compiling clap_derive v4.1.0
   Compiling aho-corasick v0.7.20
   Compiling crossbeam-epoch v0.9.13
   Compiling ahash v0.7.6
   Compiling base64 v0.13.1
   Compiling semver v1.0.16
   Compiling smallvec v1.10.0
   Compiling tinyvec_macros v0.1.1
   Compiling anyhow v1.0.69
   Compiling unicode-width v0.1.10
   Compiling tinyvec v1.6.0
   Compiling rand_core v0.6.4
   Compiling clap v4.1.6
   Compiling regex v1.7.1
   Compiling flate2 v1.0.25
   Compiling nom8 v0.2.0
   Compiling tracing-core v0.1.30
   Compiling ppv-lite86 v0.2.17
   Compiling fs-err v2.9.0
   Compiling time-core v0.1.0
   Compiling fnv v1.0.7
   Compiling rand_chacha v0.3.1
   Compiling time v0.3.19
   Compiling const-random-macro v0.1.15
   Compiling unicode-normalization v0.1.22
   Compiling webpki v0.22.0
   Compiling scroll_derive v0.11.0
   Compiling lock_api v0.4.9
   Compiling fastrand v1.9.0
   Compiling rayon-core v1.10.2
   Compiling mime v0.3.16
   Compiling percent-encoding v2.2.0
   Compiling remove_dir_all v0.5.3
   Compiling parking_lot_core v0.9.7
   Compiling portable-atomic v0.3.19
   Compiling rustls v0.20.8
   Compiling unicode-bidi v0.3.10
   Compiling toml_datetime v0.6.1
   Compiling serde_spanned v0.6.1
   Compiling const-random v0.1.15
   Compiling idna v0.3.0
   Compiling toml_edit v0.19.3
   Compiling cargo-platform v0.1.2
   Compiling toml v0.5.11
   Compiling bzip2 v0.4.4
   Compiling tempfile v3.3.0
   Compiling form_urlencoded v1.1.0
   Compiling scroll v0.11.0
   Compiling crossbeam-deque v0.8.2
   Compiling rand v0.8.5
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.3
   Compiling console v0.15.5
   Compiling sct v0.7.0
   Compiling crossbeam-channel v0.5.6
   Compiling itertools v0.10.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling regex-automata v0.1.10
   Compiling tracing-attributes v0.1.23
   Compiling num_cpus v1.15.0
   Compiling thread_local v1.1.7
   Compiling encoding_rs v0.8.32
   Compiling overload v0.1.1
   Compiling uuid v1.3.0
   Compiling pin-project-lite v0.2.9
   Compiling askama_escape v0.10.3
   Compiling plain v0.2.3
   Compiling nu-ansi-term v0.46.0
   Compiling matchers v0.1.0
   Compiling cfb v0.7.3
   Compiling askama_shared v0.12.2
   Compiling encoding v0.2.33
   Compiling digest v0.10.6
   Compiling ahash v0.3.8
   Compiling goblin v0.6.0
   Compiling unicode-linebreak v0.1.4
   Compiling charset v0.1.3
   Compiling url v2.3.1
   Compiling zip v0.6.4
   Compiling toml v0.7.2
   Compiling cargo_metadata v0.15.3
   Compiling tracing-serde v0.1.3
   Compiling webpki-roots v0.22.6
   Compiling tracing-log v0.1.3
   Compiling socks v0.3.4
   Compiling sharded-slab v0.1.4
   Compiling dirs-sys v0.3.7
   Compiling cpufeatures v0.2.5
   Compiling static_assertions v1.1.0
   Compiling number_prefix v0.4.0
   Compiling target-lexicon v0.12.6
   Compiling lzxd v0.1.4
   Compiling paste v1.0.11
   Compiling quoted_printable v0.4.7
   Compiling indicatif v0.17.3
   Compiling cab v0.4.1
   Compiling twox-hash v1.6.3
   Compiling tracing v0.1.37
   Compiling sha2 v0.10.6
   Compiling dirs v4.0.0
   Compiling ureq v2.6.2
   Compiling parking_lot v0.12.1
   Compiling chumsky v0.8.0
   Compiling msi v0.5.0
   Compiling rayon v1.6.1
   Compiling versions v4.1.0
   Compiling askama_derive v0.11.2
   Compiling cli-table v0.4.7
   Compiling cfg-expr v0.14.0
   Compiling tracing-subscriber v0.3.16
   Compiling which v4.4.0
   Compiling uniffi_checksum_derive v0.22.0
   Compiling bstr v1.3.0
   Compiling xattr v0.2.3
   Compiling filetime v0.2.20
   Compiling siphasher v0.3.10
   Compiling bytes v1.4.0
   Compiling same-file v1.0.6
   Compiling cbindgen v0.24.3
   Compiling data-encoding v2.3.3
   Compiling path-slash v0.2.1
   Compiling home v0.5.4
   Compiling shell-escape v0.1.5
   Compiling glob v0.3.1
   Compiling mailparse v0.13.8
   Compiling uniffi_meta v0.22.0
   Compiling walkdir v2.3.2
   Compiling cargo-config2 v0.1.4
   Compiling tar v0.4.38
   Compiling globset v0.4.10
   Compiling uniffi_testing v0.22.0
   Compiling rustc_version v0.4.0
   Compiling toml_datetime v0.5.1
   Compiling bincode v1.3.3
   Compiling weedle2 v4.0.0
   Compiling rfc2047-decoder v0.2.1
   Compiling rtoolbox v0.0.1
   Compiling smawk v0.3.1
   Compiling shell-words v1.1.0
   Compiling rpassword v7.2.0
   Compiling textwrap v0.16.0
   Compiling toml_edit v0.17.1
   Compiling dialoguer v0.10.3
   Compiling ignore v0.4.20
   Compiling lddtree v0.3.2
   Compiling fat-macho v0.4.6
   Compiling pyproject-toml v0.3.3
   Compiling multipart v0.18.0
   Compiling minijinja v0.30.4
   Compiling pep440 v0.2.0
   Compiling platform-info v1.0.2
   Compiling configparser v3.0.2
   Compiling normpath v1.1.0
   Compiling bytesize v1.1.0
   Compiling dunce v1.0.3
   Compiling clap_complete v4.1.2
   Compiling cargo-options v0.5.3
   Compiling xwin v0.2.10
   Compiling clap_complete_fig v4.1.1
   Compiling cargo-zigbuild v0.14.5
   Compiling clap_complete_command v0.4.0
   Compiling python-pkginfo v0.5.5
   Compiling askama v0.11.1
   Compiling uniffi_bindgen v0.22.0
   Compiling cargo-xwin v0.13.7
   Compiling maturin v0.14.13
error[E0432]: unresolved import `time::macros`
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/maturin-0.14.13/src/module_writer.rs:30:11
   |
30 | use time::macros::datetime;
   |           ^^^^^^ could not find `macros` in `time`

error: cannot determine resolution for the macro `datetime`
   --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/maturin-0.14.13/src/module_writer.rs:335:22
    |
335 |         let min_dt = datetime!(1980-01-01 0:00 UTC);
    |                      ^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

For more information about this error, try `rustc --explain E0432`.
error: could not compile `maturin` due to 2 previous errors
error: failed to compile `maturin v0.14.13`, intermediate artifacts can be found at `/var/folders/18/br1lcr9s0js75bc8l464y8_m0000gn/T/cargo-installmanoY0`


Updated 0 packages.
Failed to update maturin.
```

It seems like it fails to find the macros module in `time`.

### Your maturin version (`maturin --version`)

v0.14.13

### Your Python version (`python -V`)

python 3.11.1

### Your pip version (`pip -V`)

pip 22.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. cargo install maturin

**Comment by messense** [comment] 2023-02-21 15:01
Duplicate of https://github.com/PyO3/maturin/discussions/1494

**Closed by messense** 2023-02-21 15:01 UTC
Labels: bug
