### ISSUE TITLE
cross compile to x86_64-pc-windows-gnu from linux builds but not working

### ISSUE THREAD

**Issue by Malefaro** [PyO3/maturin#1956] opened 2024-02-23 18:03 UTC
### Bug Description

I am trying to crosscompile to windows from linux(under wsl2).

**Host:** nixos under wsl2 x86_64-unknown-linux-gnu
Linux mech 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux 

**Target:** x86_64-pc-windows-gnu

**Command I use**: 
```maturin build --target x86_64-pc-windows-gnu --zig -i python3.11```

It builds without errors, but with warning:

> ⚠️   Warning: Couldn't find the symbol `PyInit_XXX` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `XXX` as module name

I successfully install builded wheel on windows and got this when trying to use it:
```
...\Programs\Python\Python311\Lib\site-packages\XXX\__init__.py", line 1, in <module>
    from .XXX import *
ImportError: dynamic module does not define module export function (PyInit_XXX)
```

Exact same build for macos(`maturin build --target aarch64-apple-darwin --zig -i python3.11`) works well without any warning and import issues (I install builded wheel on mac M1 and then import and use library code)

PS: I checked `#[pymodule]` at `lib.rs`. It's definitely have a right name (and everything works under macos)
<details> 
  <summary> lib.rs file looks like that</summary>

```rust
use pyo3::{exceptions::PyTypeError, prelude::*};

#[pymodule]
fn XXX(py: Python, m: &PyModule) -> PyResult<()> {
}
```
</details>

PSS: I tried build to x86_64-pc-windows-msvc (`maturin build --target x86_64-pc-windows-msvc -i python3.11`) but failed due to some link issues related to clang like `cargo:warning=crypto/curve25519/../internal.h(132,10): fatal error: 'stdalign.h' file not found` (`ring` dependencies). My actual goal is crosscomiple to windows and I was able to achieve a successful build only with gnu but it's does not work even after successfull build =| So I will be grateful for any advice how to crosscompile to windows

______________________
May be usefull
<details> 
  <summary> pyproject.toml </summary>

```toml
[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "XXX"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module", "pyo3/generate-import-lib"]

[tool.poetry]
name = "XXX"
version = "0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.9.*, <4"
numpy = "^1.26.3"

[tool.poetry.group.dev.dependencies]
maturin = "^1.4.0"
jupyter = "^1.0.0"
jupyterlab-vim = "^4.1.0"


```
</details>

<details> 
  <summary> flake.nix</summary>

   ```nix
{
  description = "Dev environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay.url = "github:oxalica/rust-overlay";
  };
  outputs = { self, nixpkgs, flake-utils, rust-overlay, ... }@inputs:
    flake-utils.lib.eachDefaultSystem
      (system:
        let
          overlays = [ (import rust-overlay) ];
          pkgs = import nixpkgs {
            inherit system overlays; config.allowUnfree = true;
          };
          rust-toolchain = pkgs.symlinkJoin {
            name = "rust-toolchain";
            paths = [
              (pkgs.rust-bin.stable."1.75.0".default.override {
                targets = [ "aarch64-apple-darwin" "x86_64-unknown-linux-gnu" "x86_64-pc-windows-gnu" "x86_64-pc-windows-msvc"];
              })
              pkgs.cargo-watch
              pkgs.rust-analyzer
              pkgs.rustPlatform.rustcSrc
              pkgs.clippy
              pkgs.rustfmt
            ];
          };
        in
        {

          devShells.default = pkgs.mkShell {
            buildInputs = [
              pkgs.git
              pkgs.gnupg
              pkgs.openssl
              pkgs.gcc
              pkgs.cmake
              pkgs.protobuf
              pkgs.vscode-extensions.vadimcn.vscode-lldb
              pkgs.poetry
              pkgs.zig
              pkgs.libclang
              rust-toolchain
              gpg-gen-script
            ];
            shellHook = ''
              export OPENSSL_DIR="${pkgs.openssl.dev}"
              export OPENSSL_LIB_DIR="${pkgs.openssl.out}/lib"
              export OPENSSL_INCLUDE_DIR="${pkgs.openssl.dev}/include"

              export CODELLDB_PATH="${pkgs.vscode-extensions.vadimcn.vscode-lldb.out}"
             
            '';
          };
        }
      );
}
```
</details>

<details> 
  <summary> debug log </summary>

```logs

❯ : RUST_LOG=maturin=debug maturin build --target x86_64-pc-windows-gnu --zig -i python3.11
2024-02-23T17:38:13.588354Z DEBUG maturin::project_layout: Found pyproject.toml in working directory at "PATH_TO_PROJECT/SUB_CRATE/pyproject.toml"
2024-02-23T17:38:13.589496Z DEBUG maturin::project_layout: Using cargo manifest path from working directory: "PATH_TO_PROJECT/SUB_CRATE/Cargo.toml"
2024-02-23T17:38:13.590423Z DEBUG maturin::project_layout: Resolving cargo metadata from "PATH_TO_PROJECT/SUB_CRATE/Cargo.toml"
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
2024-02-23T17:38:13.818519Z DEBUG maturin::project_layout: Project layout resolved project_root=PATH_TO_PROJECT/SUB_CRATE python_dir=PATH_TO_PROJECT/SUB_CRATE rust_module=PATH_TO_PROJECT/SUB_CRATE/XXX python_module=PATH_TO_PROJECT/SUB_CRATE/XXX extension_name=XXX module_name=XXX
🔗 Found pyo3 bindings
2024-02-23T17:38:13.825582Z DEBUG maturin::build_options: Found CPython 3.11 in bundled sysconfig
🐍 Found CPython 3.11
📡 Using build options features from pyproject.toml
2024-02-23T17:38:14.252757Z DEBUG maturin::compile: Running env -u CARGO AR_x86_64_pc_windows_gnu="/home/USERNAME/.cache/cargo-zigbuild/0.18.0/ar" CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="/home/USERNAME/.cache/cargo-zigbuild/0.18.0/zigcc-x86_64-pc-windows-gnu.sh" CC_x86_64_pc_windows_gnu="/home/USERNAME/.cache/cargo-zigbuild/0.18.0/zigcc-x86_64-pc-windows-gnu.sh" CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_gnu="/home/USERNAME/.cache/cargo-zigbuild/0.18.0/cmake/x86_64-pc-windows-gnu-toolchain.cmake" CXX_x86_64_pc_windows_gnu="/home/USERNAME/.cache/cargo-zigbuild/0.18.0/zigcxx-x86_64-pc-windows-gnu.sh" PYO3_CONFIG_FILE="PATH_TO_PROJECT/target/maturin/pyo3-config-x86_64-pc-windows-gnu-3.11.txt" RANLIB_x86_64_pc_windows_gnu="/home/USERNAME/.cache/cargo-zigbuild/0.18.0/zigranlib.sh" WINAPI_NO_BUNDLED_LIBRARIES="1" ZIG_COMMAND="/nix/store/s7h19d99gn1arvykjvzhkx57qa4bvaj9-zig-0.11.0/bin/zig" "cargo" "rustc" "--features" "pyo3/extension-module" "--features" "pyo3/generate-import-lib" "--target" "x86_64-pc-windows-gnu" "--message-format" "json-render-diagnostics" "--manifest-path" "PATH_TO_PROJECT/SUB_CRATE/Cargo.toml" "--lib"
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
   Compiling pyo3-build-config v0.20.2
   Compiling pyo3-ffi v0.20.2
   Compiling pyo3 v0.20.2
   Compiling numpy v0.20.0
   Compiling pyo3-asyncio v0.20.0
   Compiling SUB_CRATE v0.1.0 (PATH_TO_PROJECT/SUB_CRATE)
    Finished dev [unoptimized + debuginfo] target(s) in 4.62s
⚠️   Warning: Couldn't find the symbol `PyInit_XXX` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `XXX` as module name
2024-02-23T17:38:19.427153Z DEBUG maturin::module_writer: Adding XXX-0.1.0.dist-info/METADATA
2024-02-23T17:38:19.427370Z DEBUG maturin::module_writer: Adding XXX-0.1.0.dist-info/WHEEL
2024-02-23T17:38:19.427606Z DEBUG maturin::module_writer: Adding XXX/__init__.py
2024-02-23T17:38:19.427754Z DEBUG maturin::module_writer: Adding XXX/XXX.cp311-win_amd64.pyd from PATH_TO_PROJECT/target/x86_64-pc-windows-gnu/debug/maturin/XXX.dll
2024-02-23T17:38:29.438748Z DEBUG maturin::module_writer: Adding XXX-0.1.0.dist-info/RECORD
📦 Built wheel for CPython 3.11 to PATH_TO_PROJECT/target/wheels/XXX-0.1.0-cp311-none-win_amd64.whl

```
</details>

### Your maturin version (`maturin --version`)

maturin 1.4.0

### Your Python version (`python -V`)

Python 3.11.7

### Your pip version (`pip -V`)

23.3.1

### What bindings you're using

None

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

My actual steps are: 

1. nix develop  (using flake.nix provided above) 
2. run ```maturin build --target x86_64-pc-windows-gnu --zig -i python3.11```

**Comment by messense** [comment] 2024-02-24 13:02
Duplicate of #922

**Closed by messense** 2024-02-24 13:02 UTC
Labels: bug
