### ISSUE TITLE
Add a Yocto recipe

### ISSUE THREAD

**Issue by JonathanPlasse** [PyO3/maturin#1390] opened 2023-01-05 13:29 UTC
Hi,
Thanks for this awesome project.
I use yocto for one of my projects, and I would like to swap a python library for one using `maturin` as a build backend.
I did some research, and I found no successful setup.
There was a first attempt to make a Yocto recipe for `maturin` and `orjson` [here](https://www.mail-archive.com/yocto@lists.yoctoproject.org/msg10668.html). But the thread was left unanswered.

**Comment by JonathanPlasse** [comment] 2023-01-05 15:08
I will have to look into it.
I thought I should gather the most information possible before going into it.
I will let you know if I am successful.

**Comment by moto-timo** [comment] 2023-12-10 02:15
I have support in-progress-review, but currently it is blocked because (at a minimum bzip2-sys crate) the build of maturin itself is not reproducible. ArchLinux also has maturin on its [not-reproducible list](https://reproducible.archlinux.org/).

https://lore.kernel.org/openembedded-core/cover.1701989368.git.tim.orling@konsulko.com/T/#t
https://git.yoctoproject.org/poky-contrib/log/?h=timo/maturin_1.3.2_v2

I could use help from someone more Rust savvy than me to get to the bottom of the reproducibility issue.

**Comment by messense** [comment] 2023-12-15 02:37
Sorry I won't be able to offer much help because I'm not familiar with reproducible Rust build.

**Comment by moto-timo** [comment] 2023-12-17 21:57
https://lore.kernel.org/openembedded-core/cover.1702791173.git.tim.orling@konsulko.com/T/#t

https://bugzilla.yoctoproject.org/show_bug.cgi?id=15312

FWIW, for us the reproducibility issue was purely the injection of the "TMPDIR" (where the code is being built)/"CARGO_HOME" (where the crates are downloaded) path into DW_AT_dir which was fixed with
CFLAGS:append = "-fdebug-prefix-map=${CARGO_HOME}=${TARGET_DBGSRC_DIR}/cargo_home"

If someone wants this on a Yocto Project release prior to 5.0 scarthgap, you will need to create a mixin layer to backport the changes. We do not backport such major features to stable releases.

**Comment by moto-timo** [comment] 2023-12-17 22:05
The recipe, bbclass, recipetool class and both testimage and testsdk test cases are all merged as of:
https://git.yoctoproject.org/poky/commit/?id=7d881f0214f9761990e52595d33246700c4da15c

**Closed** 2023-12-18 11:14 UTC
Labels: enhancement, distros-packaging
