### ISSUE TITLE
Publishing to PYPI fails with InvalidDistribution

### ISSUE THREAD

**Issue by ritchie46** [PyO3/maturin#2336] opened 2024-11-29 08:01 UTC
### Bug Description

The Polars release failed (twice) with:

```
Checking dist/polars-1.16.0-cp39-abi3-macosx_10_12_x86_64.whl: ERROR    InvalidDistribution: Metadata is missing required fields: Name,        
```

See full log here: https://github.com/pola-rs/polars/actions/runs/12071878482/job/33689137587

### Your maturin version (`maturin --version`)

latest (1.7.6)

### Your Python version (`python -V`)

-

### Your pip version (`pip -V`)

-

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

-

**Comment by messense** [comment] 2024-11-29 09:32
Duplicate of #2335, same underlying issue with twine not supporting metadata version 2.4 yet.

**Closed by messense** 2024-11-29 09:32 UTC
Labels: bug

**Comment by ritchie46** [comment] 2024-11-29 10:06
Great, will do!
