### ISSUE TITLE
Versioning: setuptools-scm compatibility

### ISSUE THREAD

**Issue by miili** [PyO3/maturin#1283] opened 2022-11-21 11:51 UTC
Hi all,

using https://github.com/pypa/setuptools_scm for version inference from git tags streamlines and automates the publishing workflow.
Unfortunately it is incompatible with maturin and the fixed version in `Cargo.toml`. How can maturin leverage this automation process?

I saw closed https://github.com/PyO3/maturin/issues/199, stating:

> PEP 621 also commited to having a static project.version field in the metadata just like cargo's package.version, so this a won't fix from maturin's side. If you need to do this just use sed to replace the version in a previous step of the CI pipeline

But this is not right, PEP 621 encourages `project.dynamic` fields.

Best,

M

**Comment by messense** [comment] 2022-11-21 12:02
Duplicate of https://github.com/PyO3/maturin/discussions/1267, please continue the discussion there.

**Closed by messense** 2022-11-21 12:02 UTC
Labels: enhancement

**Comment by rmorshea** [comment] 2024-09-23 21:32
Are there any plans to support similar functionality within Maturin itself?
